apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiseti-pod-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: kubedevio/web-page:green
          ports:
            - containerPort: 80

---
# Expondo Aplicação no Cluster /POD 
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80 
      nodePort: 30000
  type: LoadBalancer